
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 03 05:02:24 COT 2016
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHA = 27;
  public static final int MULT = 10;
  public static final int CHAR = 41;
  public static final int RET = 36;
  public static final int OUTPUT = 35;
  public static final int INPUT = 34;
  public static final int INTEGER = 37;
  public static final int RESTA = 9;
  public static final int INT = 22;
  public static final int FIN = 26;
  public static final int string = 28;
  public static final int LLAVECERRADA = 14;
  public static final int IDENTIFICADOR = 39;
  public static final int MENORIGUAL = 4;
  public static final int CORCHIZQ = 20;
  public static final int PARENTESISCERRADO = 15;
  public static final int BOOL = 24;
  public static final int DIV = 11;
  public static final int INCREMENTO = 19;
  public static final int SUMA = 8;
  public static final int IF = 29;
  public static final int FLOA = 23;
  public static final int MAYORIGUAL = 3;
  public static final int EOF = 0;
  public static final int EQUAL = 16;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int MENOR = 17;
  public static final int LLAVEABIERTA = 13;
  public static final int MAYOR = 18;
  public static final int CORCHDER = 21;
  public static final int PARENTESISABIERTO = 12;
  public static final int IGUALIGUAL = 2;
  public static final int WHILE = 32;
  public static final int THEN = 30;
  public static final int PELSE = 31;
  public static final int DOSP = 7;
  public static final int BOOLEANO = 40;
  public static final int STRING = 42;
  public static final int INICIO = 25;
  public static final int TER = 6;
  public static final int FLOTANTE = 38;
  public static final int DO = 33;
}

